#!/usr/bin/env bash
# Regenerate THIRD-PARTY-NOTICES.txt from the ACTUAL dependency graph.
#
# Athar redistributes third-party code one way now: the Go modules compiled
# into the collector/dashboard binary (modernc.org/sqlite, pgx,
# maxminddb-golang, x/crypto and their transitive deps). MIT, BSD, ISC,
# Apache-2.0, MPL-2.0 and OFL-1.1 all require the copyright notice and
# licence text to accompany every copy.
#
# The npm section below is expected to come back near-empty: the dashboard
# is hand-written HTML/CSS/JS with zero third-party code (see
# backend/internal/webui), and package.json's only dependencies are
# devDependencies (esbuild for the tracker build, Playwright for
# screenshots/tests) — neither ships in the binary, so `--production` (below)
# has nothing to report. The step is kept rather than deleted so a future
# runtime npm dependency cannot slip in unnoticed.
#
#     ./scripts/gen-notices.sh
#
# THIRD-PARTY-NOTICES.txt is committed at the repo root. It is NOT hand
# maintained — this script is the only thing that should ever change it.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

OUT="THIRD-PARTY-NOTICES.txt"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# --- Go modules. The rules file allows the licences Athar's dependency graph
# is known to use (MIT, BSD, Apache-2.0, MPL-2.0) and denies GPL/AGPL/LGPL/
# SSPL/BUSL — a copyleft or source-available dependency has no business being
# compiled into a binary Athar dual-licenses under MIT OR Apache-2.0.
DETECTOR="$(command -v go-licence-detector || true)"
if [[ -z "$DETECTOR" ]]; then
  echo "==> installing go.elastic.co/go-licence-detector@v0.10.0"
  GOBIN="$TMP/bin" go install go.elastic.co/go-licence-detector@v0.10.0
  DETECTOR="$TMP/bin/go-licence-detector"
fi

echo "==> resolving Go module graph"
go mod download
go list -m -json all | "$DETECTOR" \
  -includeIndirect \
  -rules scripts/notices/go-licence-rules.json \
  -noticeTemplate scripts/notices/go-modules.tmpl \
  -noticeOut "$TMP/go-notices.txt"

# --- npm packages actually bundled into dist (production deps only).
echo "==> resolving npm dependency graph"
[[ -d node_modules ]] || npm ci
npx --yes license-checker-rseidelsohn \
  --production --json --excludePrivatePackages --start . \
  | node scripts/notices/npm-notices.mjs > "$TMP/npm-notices.txt"

echo "==> composing $OUT"
{
  cat <<'HEADER'
================================================================================
Athar — THIRD-PARTY NOTICES
================================================================================

This file is generated by scripts/gen-notices.sh from the actual dependency
graph. Do not edit it by hand.

Athar is dual-licensed MIT OR Apache-2.0 (see LICENSE-MIT / LICENSE-APACHE).
It bundles the third-party software listed below. Each entry gives the
component name, its version, the licence it is distributed under, and the
full text of that licence, as those licences require.

HEADER

  echo "================================================================================"
  echo "npm packages (bundled into the Athar dashboard)"
  echo "================================================================================"
  echo
  cat "$TMP/npm-notices.txt"

  echo "================================================================================"
  echo "Go standard library (compiled into the athar binary)"
  echo "================================================================================"
  echo
  echo "--------------------------------------------------------------------------------"
  echo "Component : The Go Programming Language standard library"
  echo "Version   : $(go env GOVERSION)"
  echo "Licence   : BSD-3-Clause (plus the Go patent grant, reproduced below)"
  echo "--------------------------------------------------------------------------------"
  echo
  cat "$(go env GOROOT)/LICENSE"
  echo
  cat "$(go env GOROOT)/PATENTS"
  echo

  echo "================================================================================"
  echo "Go modules (compiled into the athar binary)"
  echo "================================================================================"
  echo
  cat "$TMP/go-notices.txt"
} > "$OUT"

echo "==> wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines)"
