// Package tracker serves the client-side tracking script.
//
// Two copies of the script are embedded: the commented source (athar.js) and a
// minified build (athar.min.js, generated by `make tracker`). The minified one
// is what visitors' browsers download; the source is what people read, and is
// served at ?source=1 so anyone can check that the script running on a site they
// visit is the script this repository publishes.
//
// The minified file is committed rather than gitignored so that `go build`
// alone produces a working binary — a Go toolchain should be enough to build
// Athar, without also needing Node.
package tracker

import (
	"bytes"
	"compress/gzip"
	"crypto/sha256"
	"embed"
	"encoding/base64"
	"fmt"
	"net/http"
	"strconv"
	"strings"
	"sync"
	"time"
)

//go:embed athar.js athar.min.js
var files embed.FS

// Handler serves the tracker script.
type Handler struct {
	minified []byte
	source   []byte

	gzipOnce sync.Once
	gzipped  []byte

	etag     string
	modTime  time.Time
	sriHash  string
}

// New loads the embedded scripts.
func New() (*Handler, error) {
	min, err := files.ReadFile("athar.min.js")
	if err != nil {
		return nil, fmt.Errorf("tracker: read athar.min.js: %w", err)
	}
	src, err := files.ReadFile("athar.js")
	if err != nil {
		return nil, fmt.Errorf("tracker: read athar.js: %w", err)
	}

	sum := sha256.Sum256(min)
	return &Handler{
		minified: min,
		source:   src,
		etag:     `"` + fmt.Sprintf("%x", sum[:8]) + `"`,
		sriHash:  "sha256-" + base64.StdEncoding.EncodeToString(sum[:]),
		// The scripts are compiled in, so their content cannot change without a
		// new binary. A fixed build-time modtime keeps conditional requests
		// meaningful without reading the clock per request.
		modTime: time.Unix(0, 0).UTC(),
	}, nil
}

// SRI returns the Subresource Integrity hash of the served script, so a site
// owner can pin the exact bytes their pages will execute.
func (h *Handler) SRI() string { return h.sriHash }

// Size returns the byte size of the minified script and its gzipped form — the
// two numbers that actually describe what a visitor downloads.
func (h *Handler) Size() (raw, gzipped int) {
	return len(h.minified), len(h.gzip())
}

// gzip compresses the minified script once, lazily.
func (h *Handler) gzip() []byte {
	h.gzipOnce.Do(func() {
		var buf bytes.Buffer
		zw, _ := gzip.NewWriterLevel(&buf, gzip.BestCompression)
		_, _ = zw.Write(h.minified)
		_ = zw.Close()
		h.gzipped = buf.Bytes()
	})
	return h.gzipped
}

// ServeHTTP serves the script. `?source=1` returns the readable original.
func (h *Handler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet && r.Method != http.MethodHead {
		w.Header().Set("Allow", "GET, HEAD")
		w.WriteHeader(http.StatusMethodNotAllowed)
		return
	}

	head := w.Header()
	head.Set("Content-Type", "application/javascript; charset=utf-8")
	// The script is fetched from third-party pages, so it must be readable
	// cross-origin. It is a static public asset: there is nothing to leak.
	head.Set("Access-Control-Allow-Origin", "*")
	head.Set("X-Content-Type-Options", "nosniff")

	if r.URL.Query().Get("source") != "" {
		// The readable copy is small enough not to bother caching hard, and
		// serving it fresh means "view the source of what I'm running" always
		// shows the current binary's copy.
		head.Set("Cache-Control", "public, max-age=300")
		http.ServeContent(w, r, "athar.js", h.modTime, bytes.NewReader(h.source))
		return
	}

	// Four hours, revalidatable. Long enough that the script is effectively
	// cached, short enough that upgrading Athar reaches visitors the same day.
	head.Set("Cache-Control", "public, max-age=14400, must-revalidate")
	head.Set("ETag", h.etag)

	if match := r.Header.Get("If-None-Match"); match != "" && strings.Contains(match, h.etag) {
		w.WriteHeader(http.StatusNotModified)
		return
	}

	body := h.minified
	if acceptsGzip(r) {
		body = h.gzip()
		head.Set("Content-Encoding", "gzip")
		head.Add("Vary", "Accept-Encoding")
	}
	head.Set("Content-Length", strconv.Itoa(len(body)))

	if r.Method == http.MethodHead {
		w.WriteHeader(http.StatusOK)
		return
	}
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(body)
}

func acceptsGzip(r *http.Request) bool {
	for _, enc := range strings.Split(r.Header.Get("Accept-Encoding"), ",") {
		if name, _, _ := strings.Cut(strings.TrimSpace(enc), ";"); name == "gzip" {
			return true
		}
	}
	return false
}
